spring.application.name=pharmacy

spring.datasource.url=jdbc:mysql://localhost:3306/pharmapulse_db
spring.datasource.username=project
spring.datasource.password=Jeni@1706

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
